### ISSUE TITLE
使用的图片数组问题

### ISSUE THREAD

**Issue by tangzzz-fan** [yixiangboy/YXFilmSelectView#1]
指定图片数组，可以不使用.jpg格式结尾的字符数组，造成绘制时错误(sent to unrecognized selector)。将给定的图片数组换成图片名数组(没有.jpg结尾)的，初始化时图片时，使用[uiimage imagename:]便不会造成错误。

**Comment by yixiangboy** [comment]
这只是一个demo而已，具体需求还是需要改动一点的
